version: '3'
services:
  
  webserver:
    build: ./backend_config
    volumes: 
      - ../smartcontract:/smartcontract
      - ../backend/back.py:/backend/back.py
      - ../backend/static:/backend/static
      - ../backend/db.json:/backend/db.json
      - ./backend_config/config.json:/backend/config.json
    networks: 
      - mynetwork
  
  reverseproxy:    
    image: nginx:latest
    volumes:
      - ./nginx-config-cert/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-config-cert/cert.crt:/etc/nginx/cert.crt
      - ./nginx-config-cert/cert.key:/etc/nginx/cert.key
      - ./nginx-config-cert/frontend/build:/localfiles
    ports:
       - 443:443
       - 80:80
    networks: 
      - mynetwork

networks:
  mynetwork:
    driver: bridge